export const permissions = [
  { label: "Dashboard", value: "dashboard" },
  { label: "Add Sub Admin", value: "subAdmin" },
  { label: "Customer", value: "customer" },
  { label: "Restaurants", value: "restaurant" },
  { label: "Vendor", value: "vendor" },
  { label: "Delivery Agent", value: "deliveryAgent" },
  // { label: "Delivery Charge", value: "deliveryCharge" },
  { label: "Order", value: "order" },
  { label: "Reviews", value: "review" },
  { label: "Offers", value: "offer" },
  { label: "Application Request", value: "applicationRequest" },
  { label: "Delivery Charges", value: "deliveryCharges" },
  { label: "Zones", value: "zones" },
  { label: "Notifications", value: "notifications" },
  { label: "Tickets", value: "tickets" },
  { label: "Content", value: "content" },
  { label: "Spotlight", value: "spotlight" },
  { label: "Available Cities", value: "availableCities" },
  { label: "Terms and Policy", value: "termsandPolicy" },
];
